services:
  app:
    container_name: portfolio-paradise
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_DIRECTUS_URL: ${NEXT_PUBLIC_DIRECTUS_URL}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
    network_mode: host
    environment:
      PORT: "3004"
    env_file: .env
    restart: unless-stopped
